version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: heunet-server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    volumes:
      - db_data:/app/src/databases
    networks:
      - heunet-network
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: heunet-client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - heunet-network
    restart: unless-stopped

networks:
  heunet-network:
    driver: bridge
volumes:
  db_data:
